name = "LazyBandedMatrices"
uuid = "d7e5e226-e90b-4449-9968-0f923699bf6f"
authors = ["Sheehan Olver <solver@mac.com>"]
version = "0.0.2"

[deps]
ArrayLayouts = "4c555306-a7a7-4459-81d9-ec55ddd5c99a"
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
BlockBandedMatrices = "ffab5731-97b5-5995-9138-79e8c1846df0"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
MatrixFactorizations = "a3b82374-2e81-5b9e-98ce-41277c0e4c87"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
ArrayLayouts = "0.1"
FillArrays = "0.8"
BandedMatrices = "0.14"
BlockBandedMatrices = "0.6"
LazyArrays = "0.14.3"
MatrixFactorizations = "0.2.1"
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
